### ISSUE TITLE
Discovery not working

### ISSUE THREAD

**Issue by morphx666** [Jazea/Onvif.Core#24]
This is the code I'm using to try the discovery functionality:

```csharp
private readonly DiscoveryService discoveryService;
.
.
.
discoveryService = new();
discoveryService.DiscoveredDevices.CollectionChanged += (object s, NotifyCollectionChangedEventArgs e) => {
    Debugger.Break();
};
Task.Run(discoveryService.Start);
```

Is this correct?
From what I have found is that `client.ReceiveAsync().ConfigureAwait(false)` from the `ReceiveAsync()` function never returns causing the main loop to timeout.

Am I doing something wrong?

**Comment by morphx666** [comment]
I just found out that if I modify the `UdpClientWrapper` initialization to use my computer's LAN IP address, it seems to work fine.
So, changing this line of code in the `WSDiscovery` class does the trick:

```csharp
return Discover(timeout, new UdpClientWrapper("192.168.1.2", 0), cancellationToken);
```

Note that using 127.0.0.1 won't work.

**Comment by 3ricj** [comment]
I'm really confused by this fix -- I still don't see any method for a consume of this class to be able to use it.  Meaning, I can't pass into the Discovery class a subnet or port -- I have to modify the class and compile it with my program?    Ugh.  I hope I'm missing something here.

**Comment by morphx666** [comment]
Yes, I had to modify the code and re-compile it.

First, I added a new constructor to the `DiscoveryService` class;

``` csharp
public DiscoveryService(string ipAddress) : this() {
    DiscoveredDevices = new ObservableCollection<DiscoveryDevice>();
    wsDiscovery = new WSDiscovery(ipAddress);
}
```
Then, added a new global variable to the `WSDiscovery` class called `ipAddress`.
Also added a new constructor to the same class which accepts the `ipAddress` as a parameter:

``` csharp
public WSDiscovery(string ipAddress) : this() {
    this.ipAddress = ipAddress;
}
```

And finally, I modified the `Discover` method to handle the case where the `ipAddress` is set:

``` csharp
public Task<IEnumerable<DiscoveryDevice>> Discover(int timeout, CancellationToken cancellationToken = default) {
    if(ipAddress != string.Empty)
        return Discover(timeout, new UdpClientWrapper(ipAddress, 0), cancellationToken);
    else
        return Discover(timeout, new UdpClientWrapper(), cancellationToken);
}
```

All this allows me to instantiate a new `DiscoveryService` using my device's internal LAN IP address:

``` csharp
public class TestDiscovery {
    private readonly DiscoveryService discoveryService;

    public TestDiscovery() {
        discoveryService = new("192.168.1.2");
        discoveryService.DiscoveredDevices.CollectionChanged += (object s, NotifyCollectionChangedEventArgs e) => {
            foreach(DiscoveryDevice device in e.NewItems) {
                Debug.WriteLine($"{device.Name} {device.Model}\r\n" +
                                    $"\t{device.XAdresses.Aggregate((c, n) => c + ", " + n)}\r\n" +
                                    $"\t{device.Types.Aggregate((c, n) => c + ", " + n)}");
            }
        };
        Task.Run(discoveryService.Start);
    }
}
```

**Comment by differentrain** [comment]
> I'm really confused by this fix -- I still don't see any method for a consume of this class to be able to use it. Meaning, I can't pass into the Discovery class a subnet or port -- I have to modify the class and compile it with my program? Ugh. Am I missing something here?

@morphx666 Sorry, I forgot to update `Start` Method, Now this problem is fixed.
