### ISSUE TITLE
Useless repository

### ISSUE THREAD

**Issue by askrinnik** [Jazea/Onvif.Core#3]
I see no source code or any mention of where can I find the library
Absolutely useless repository

**Comment by mrdx-orb** [comment]
There is more for this project on NuGet
https://www.nuget.org/packages/Onvif.Core/

**Comment by askrinnik** [comment]
@mrdx-orb , I see nothing new on NuGet
Anyway, if it is an open-source project, where is the source code?

**Comment by wei-taoxu** [comment]
> @mrdx-orb , I see nothing new on NuGet Anyway, if it is an open-source project, where is the source code?

Uploaded code
