### ISSUE TITLE
PTZ continuous motion causes exception on Bosch cameras

### ISSUE THREAD

**Issue by ssi-jmandrell** [Jazea/Onvif.Core#30]
I have a Bosch camera that will not respond to a PTZ continuous move request. I looked at the low-level response from the camera and it is complaining that "timeout is an unsupported field". I need a way to send a continuous move request without the timeout field. I looked through the current code but nothing jumped out at me providing a way to do this.

**Comment by differentrain** [comment]
I'm not sure whether these works are effective. 
Anyway, try this branch https://github.com/Jazea/Onvif.Core/tree/Issues30,
and set timeout(argument or property..) to `null` 
e.g.  
`await camera.MoveAsync(moveType: MoveType.Continuous, vector: ptzVector,  speed: ptzSpeed, timeout: null) `

**Comment by ssi-jmandrell** [comment]
Thanks! I will set up the camera and give this a try.

**Comment by ssi-jmandrell** [comment]
That worked quite well and fixed the problem, thank you!
